export const carModel = [
  { id: 1, name: "Aston Martin DB9", productId: 1 },
  { id: 2, name: "Aston Martin Vantage", productId: 1 },
  { id: 3, name: "Audi A4", productId: 1 },
  { id: 4, name: "Audi S4", productId: 1 },
  { id: 5, name: "Bentley Continental GT", productId: 1 },
  { id: 6, name: "BMW M3 GTR", productId: 1 },
  { id: 7, name: "BMW M5", productId: 1 },
  { id: 8, name: "BMW M6", productId: 1 },
  { id: 9, name: "Cadillac CTS", productId: 1 },
  { id: 10, name: "Cadillac XLR", productId: 1 },
  { id: 11, name: "Chevrolet Camaro SS", productId: 1 },
  { id: 12, name: "Chevrolet Corvette C6", productId: 1 },
  { id: 13, name: "Chevrolet Corvette Z06", productId: 1 },
  { id: 14, name: "Dodge Challenger SRT8", productId: 1 },
  { id: 15, name: "Dodge Viper GTS", productId: 1 },
  { id: 16, name: "Dodge Viper SRT-10", productId: 1 },
  { id: 17, name: "Ferrari 360 Modena", productId: 1 },
  { id: 18, name: "Ferrari F430", productId: 1 },
  { id: 19, name: "Ford GT", productId: 1 },
  { id: 20, name: "Ford GT40", productId: 1 },
  { id: 21, name: "Ford Mustang GT", productId: 1 },
  { id: 22, name: "Honda NSX", productId: 1 },
  { id: 23, name: "Honda S2000", productId: 1 },
  { id: 24, name: "Jaguar XKR", productId: 1 },
  { id: 25, name: "Jaguar XK8", productId: 1 },
  { id: 26, name: "Lamborghini Gallardo", productId: 1 },
  { id: 27, name: "Lamborghini Murcielago", productId: 1 },
  { id: 28, name: "Lotus Elise", productId: 1 },
  { id: 29, name: "Lotus Esprit", productId: 1 },
  { id: 30, name: "Mazda RX-7", productId: 1 },
  { id: 31, name: "Mazda RX-8", productId: 1 },
  { id: 32, name: "Mazda MX-5 Miata", productId: 1 },
  { id: 33, name: "Mercedes Benz CLK 500", productId: 1 },
  { id: 34, name: "Mercedes Benz CLK 55 AMG", productId: 1 },
  { id: 35, name: "Mercedes Benz SL 55 AMG", productId: 1 },
  { id: 36, name: "Mitsubishi Lancer Evolution VIII", productId: 1 },
  { id: 37, name: "Mitsubishi 3000GT", productId: 1 },
  { id: 38, name: "Nissan 350Z", productId: 1 },
  { id: 39, name: "Nissan GT-R", productId: 1 },
  { id: 40, name: "Nissan Skyline GT-R R34", productId: 1 },
  { id: 41, name: "Pontiac GTO", productId: 1 },
  { id: 42, name: "Pontiac Trans Am", productId: 1 },
  { id: 43, name: "Porsche 911 Carrera S", productId: 1 },
  { id: 44, name: "Porsche 911 Turbo", productId: 1 },
  { id: 45, name: "Porsche Boxster S", productId: 1 },
  { id: 46, name: "Subaru Impreza WRX STI", productId: 1 },
  { id: 47, name: "Subaru WRX STI", productId: 1 },
  { id: 48, name: "Toyota 86", productId: 1 },
  { id: 49, name: "Toyota Supra", productId: 1 },
  { id: 50, name: "Volkswagen Golf GTI", productId: 1 },
  { id: 51, name: "Volvo S60 R", productId: 1 },
];